
@startuml

Mastermind *-down-> "2" Jugador
Mastermind *-down- Tablero
Mastermind *-down-> Turno


Jugador <|-down- Maestro
Jugador <|-down- Adivinador

Turno --> "2" Jugador

Tablero *-- CombinaciónSecreta
Tablero --> "0..10" CombinaciónPropuesta
Tablero --> "1..10" ComprobarCombinación 

CombinaciónSecreta-up-|> Combinación 
CombinaciónPropuesta -up-|> Combinación 

Maestro --> ElegirCombinaciónSecreta
ElegirCombinaciónSecreta --> CombinaciónSecreta
Adivinador-->"1..10" ProponerCombinación
ProponerCombinación --> CombinaciónPropuesta 

ComprobarCombinación --> CombinaciónSecreta
ComprobarCombinación --> CombinaciónPropuesta
ComprobarCombinación --> Resultado

Resultado *--> "0..4" FichitasNegras
Resultado *--> "0..4" FichitasBlancas

ResultadoFinal -up-|> Resultado

Combinación *--> "4" Posición

Posición *--> Color

FichitasNegras *--> Posición

Verde -up-|> Color
Rojo -up-|> Color
Azul -up-|> Color
Amarilla -up-|> Color
Rosas -up-|> Color
Violeta -up-|> Color

@enduml
